@startuml
[*] --> 注文作成中 : 初期状態
注文作成中 --> 注文確認待ち : ユーザーが商品をカートに追加する
注文確認待ち --> 支払い待ち : 注文を確定する
支払い待ち --> 配送準備中 : 支払いが完了する
配送準備中 --> 配送済み :配送が完了
支払い待ち --> キャンセル済み : 注文をキャンセルする
支払い待ち --> 支払い失敗 :支払いを通知
支払い失敗 --> 支払い待ち 